 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/.DS_Store | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo.txt | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_DEBUG.txt | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_DEBUG_2.txt | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_noStopWord.txt | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_noStopWord_format2.txt | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_noStopWord_WORD_ID.txt | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_noStopWord_WORD_ID.txt_format_2.txt | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_noStopWord_WORD_ID_format2.txt | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_WORD_ID.txt | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_URLs_NOT_exists_in_sample_ds1_AND_ground_truth_DATETIME_exists_AddLineNo_CHRONO.txt | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/cosine_sim.txt | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/debug.txt | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/debug_cosine_sim.txt | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/debug_cosine_sim_backup.txt | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/docID_CosineSim.txt | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/docID_CosineSim_NORMALIZ.txt | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/docID_Jaccard.txt | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/docID_Jaccard_NORMALIZ.txt | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/docID_totalNewWords.txt | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/docID_totalNewWords_NORMALIZ.txt | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/ds1_URLs_ground_truth_notExists_in_ds1.txt | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/ground_truth.txt | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/neigh10 | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/neigh15 | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/neigh2 | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/neigh3 | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/neigh4 | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/neigh5 | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/shell_output_cat_command.sh | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/unique_word_vocabulary.txt | grep -i nepal >> out_nepal.txt
 cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/.DS_Store | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_DEBUG.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_DEBUG_2.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_noStopWord.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_noStopWord_format2.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_noStopWord_WORD_ID.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_noStopWord_WORD_ID.txt_format_2.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_noStopWord_WORD_ID_format2.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_WORD_ID.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_URLs_NOT_exists_in_sample_ds1_AND_ground_truth_DATETIME_exists_AddLineNo_CHRONO.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/cosine_sim.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/debug.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/debug_cosine_sim.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/debug_cosine_sim_backup.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/docID_CosineSim.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/docID_CosineSim_NORMALIZ.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/docID_Jaccard.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/docID_Jaccard_NORMALIZ.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/docID_totalNewWords.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/docID_totalNewWords_NORMALIZ.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/ds1_URLs_ground_truth_notExists_in_ds1.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/ground_truth.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/neigh10 | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/neigh15 | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/neigh2 | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/neigh3 | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/neigh4 | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/neigh5 | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/shell_output_cat_command.sh | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/unique_word_vocabulary.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/.DS_Store | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_DEBUG.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_DEBUG_2.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_noStopWord.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_noStopWord_format2.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_noStopWord_WORD_ID.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_noStopWord_WORD_ID.txt_format_2.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_noStopWord_WORD_ID_format2.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_WORD_ID.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_URLs_NOT_exists_in_sample_ds1_AND_ground_truth_DATETIME_exists_AddLineNo_CHRONO.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/cosine_sim.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/debug.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/debug_cosine_sim.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/debug_cosine_sim_backup.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/docID_CosineSim.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/docID_CosineSim_NORMALIZ.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/docID_Jaccard.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/docID_Jaccard_NORMALIZ.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/docID_totalNewWords.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/docID_totalNewWords_NORMALIZ.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/ds1_URLs_ground_truth_notExists_in_ds1.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/ground_truth.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/neigh10 | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/neigh15 | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/neigh2 | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/neigh3 | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/neigh4 | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/neigh5 | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/shell_output_cat_command.sh | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/unique_word_vocabulary.txt | grep -i nepal >> out_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/.DS_Store | grep -i nepal >> out__.DS_Store_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo.txt | grep -i nepal >> out___merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo.txt_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt | grep -i nepal >> out___merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt | grep -i nepal >> out___merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_DEBUG.txt | grep -i nepal >> out___merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_DEBUG.txt_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_DEBUG_2.txt | grep -i nepal >> out___merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_DEBUG_2.txt_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_noStopWord.txt | grep -i nepal >> out___merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_noStopWord.txt_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_noStopWord_format2.txt | grep -i nepal >> out___merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_noStopWord_format2.txt_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_noStopWord_WORD_ID.txt | grep -i nepal >> out___merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_noStopWord_WORD_ID.txt_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_noStopWord_WORD_ID.txt_format_2.txt | grep -i nepal >> out___merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_noStopWord_WORD_ID.txt_format_2.txt_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_noStopWord_WORD_ID_format2.txt | grep -i nepal >> out___merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_noStopWord_WORD_ID_format2.txt_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_WORD_ID.txt | grep -i nepal >> out___merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_nodup_DATETIME_exists_AddLineNo_CHRONO.txt_TF_IDF.txt_WORD_ID.txt_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/_merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_URLs_NOT_exists_in_sample_ds1_AND_ground_truth_DATETIME_exists_AddLineNo_CHRONO.txt | grep -i nepal >> out___merged_all_tokens_normalized_matched_merged_with_gTruth_TP_nodup_URLs_NOT_exists_in_sample_ds1_AND_ground_truth_DATETIME_exists_AddLineNo_CHRONO.txt_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/cosine_sim.txt | grep -i nepal >> out__cosine_sim.txt_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/debug.txt | grep -i nepal >> out__debug.txt_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/debug_cosine_sim.txt | grep -i nepal >> out__debug_cosine_sim.txt_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/debug_cosine_sim_backup.txt | grep -i nepal >> out__debug_cosine_sim_backup.txt_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/docID_CosineSim.txt | grep -i nepal >> out__docID_CosineSim.txt_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/docID_CosineSim_NORMALIZ.txt | grep -i nepal >> out__docID_CosineSim_NORMALIZ.txt_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/docID_Jaccard.txt | grep -i nepal >> out__docID_Jaccard.txt_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/docID_Jaccard_NORMALIZ.txt | grep -i nepal >> out__docID_Jaccard_NORMALIZ.txt_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/docID_totalNewWords.txt | grep -i nepal >> out__docID_totalNewWords.txt_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/docID_totalNewWords_NORMALIZ.txt | grep -i nepal >> out__docID_totalNewWords_NORMALIZ.txt_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/ds1_URLs_ground_truth_notExists_in_ds1.txt | grep -i nepal >> out__ds1_URLs_ground_truth_notExists_in_ds1.txt_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/ground_truth.txt | grep -i nepal >> out__ground_truth.txt_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/neigh10 | grep -i nepal >> out__neigh10_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/neigh15 | grep -i nepal >> out__neigh15_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/neigh2 | grep -i nepal >> out__neigh2_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/neigh3 | grep -i nepal >> out__neigh3_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/neigh4 | grep -i nepal >> out__neigh4_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/neigh5 | grep -i nepal >> out__neigh5_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/shell_output_cat_command.sh | grep -i nepal >> out__shell_output_cat_command.sh_nepal.txt
cat  out_nepal.txt >> all.txt cat /Users/lenin/Downloads/#problems/p8/work-FullArticle/samples/sample.on.keywords_ds1/final/prepare.cronological.ds1/unique_word_vocabulary.txt | grep -i nepal >> out__unique_word_vocabulary.txt_nepal.txt
cat  out_nepal.txt >> all.txt